// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWHMNUkVCdoC2r4PnAlYx8CvHwJub6cDA',
    appId: '1:209073759380:web:287b54601dc16d6ba68081',
    messagingSenderId: '209073759380',
    projectId: 'strife-86649',
    authDomain: 'strife-86649.firebaseapp.com',
    storageBucket: 'strife-86649.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5_Bhirz2OXGeDUfySHKc63coO1kMW9ZQ',
    appId: '1:209073759380:android:15ba8b97952884dea68081',
    messagingSenderId: '209073759380',
    projectId: 'strife-86649',
    storageBucket: 'strife-86649.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD46b1-7kOKXqvIlPoy27dy47ZmYJoiSHo',
    appId: '1:209073759380:ios:f50ed833bff5ec48a68081',
    messagingSenderId: '209073759380',
    projectId: 'strife-86649',
    storageBucket: 'strife-86649.appspot.com',
    iosClientId: '209073759380-aeb0c9s3t1hobekfotpu27tsndfbses4.apps.googleusercontent.com',
    iosBundleId: 'com.example.strife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD46b1-7kOKXqvIlPoy27dy47ZmYJoiSHo',
    appId: '1:209073759380:ios:f50ed833bff5ec48a68081',
    messagingSenderId: '209073759380',
    projectId: 'strife-86649',
    storageBucket: 'strife-86649.appspot.com',
    iosClientId: '209073759380-aeb0c9s3t1hobekfotpu27tsndfbses4.apps.googleusercontent.com',
    iosBundleId: 'com.example.strife',
  );
}
